name: Release

on:
  push:
    branches:
    - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'
    - run: dotnet build --configuration Release
    - run: dotnet nuget push MisskeyDotNet/bin/Release/MisskeyDotNet.*.nupkg -k $NUGET_OLG_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_OLG_API_KEY: ${{ secrets.NUGET_OLG_API_KEY }}