name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'
    - run: dotnet build --configuration Release
    - run: dotnet nuget push MisskeyDotNet/bin/Release/MisskeyDotNet.*.nupkg -k $NUGET_OLG_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_OLG_API_KEY: ${{ secrets.NUGET_OLG_API_KEY }}
    - name: GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          - Misskey v13で正常に動作しない問題を修正
        draft: false
        prerelease: false